filter:
    paths: [src/*]
    excluded_paths: [examples/*, tests/*]
checks:
    php: true
tools:
    php_code_sniffer:
        config:
            standard: "PSR2"
    external_code_coverage: true
build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run